// NEXIM.LutGen — dev-only tool that generates two binary data assets:
//
//   1. k-table files (.ktbl) in data/hitran_kdist/
//      Correlated-k distribution tables for H₂O, derived from a physics-based
//      aggregate line model calibrated to HITRAN2020 band integrals
//      (Gordon et al. 2022, JQSRT 277:107949, doi:10.1016/j.jqsrt.2021.107949).
//      One file per wavelength band per species: H2O_0000.ktbl … H2O_0249.ktbl.
//
//   2. Atmospheric LUT file (nexim_v1.lut) in data/lut/
//      Pre-computed 5-D (SZA × VZA × AOD × WVC × λ) lookup table generated by
//      driving AccurateAtmosphericRT (Mode 2, CKD+DISORT 8-stream) over the full
//      axis grid with the k-tables just generated.  Used by FastAtmosphericRT (Mode 1)
//      for < 10 ms preview rendering.
//
// Usage:
//   NEXIM.LutGen ktables [--ktables-dir <path>] [--threads <n>]
//   NEXIM.LutGen lut     [--ktables-dir <path>] [--lut-file <path>] [--threads <n>]
//   NEXIM.LutGen all     [--ktables-dir <path>] [--lut-file <path>] [--threads <n>]
//
// Defaults:
//   --ktables-dir  data/hitran_kdist
//   --lut-file     data/lut/nexim_v1.lut
//   --threads      all logical processors

using NEXIM.LutGen;

string ktablesDir = "data/hitran_kdist";
string lutFile    = "data/lut/nexim_v1.lut";
int    threads    = Environment.ProcessorCount;
string command    = "all";

for (int i = 0; i < args.Length; i++)
{
    switch (args[i].ToLowerInvariant())
    {
        case "ktables": case "lut": case "all":
            command = args[i].ToLowerInvariant(); break;
        case "--ktables-dir" when i + 1 < args.Length:
            ktablesDir = args[++i]; break;
        case "--lut-file" when i + 1 < args.Length:
            lutFile = args[++i]; break;
        case "--threads" when i + 1 < args.Length && int.TryParse(args[++i], out int t):
            threads = Math.Max(1, t); break;
        case "--help": case "-h":
            PrintHelp(); return 0;
    }
}

Console.WriteLine("NEXIM.LutGen  —  hyperspectral atmospheric data generator");
Console.WriteLine($"  Command      : {command}");
Console.WriteLine($"  K-tables dir : {ktablesDir}");
Console.WriteLine($"  LUT file     : {lutFile}");
Console.WriteLine($"  Threads      : {threads}");
Console.WriteLine();

try
{
    if (command is "ktables" or "all")
    {
        Console.WriteLine("=== Step 1/2: Generating k-distribution tables ===");
        KTableGeneratorTask.GenerateAll(ktablesDir, threads);
        Console.WriteLine("K-tables complete.\n");
    }

    if (command is "lut" or "all")
    {
        Console.WriteLine("=== Step 2/2: Generating atmospheric LUT ===");
        LutGridGenerator.Generate(ktablesDir, lutFile, threads);
        Console.WriteLine("LUT complete.\n");
    }

    Console.WriteLine("Done.");
    return 0;
}
catch (Exception ex)
{
    Console.Error.WriteLine($"FATAL: {ex.Message}");
    Console.Error.WriteLine(ex.StackTrace);
    return 1;
}

static void PrintHelp()
{
    Console.WriteLine("""
    NEXIM.LutGen — Generate pre-computed atmospheric data assets.

    COMMANDS:
      ktables   Generate k-distribution table files only.
      lut       Generate LUT file only (requires k-tables).
      all       (default) Generate k-tables then LUT.

    OPTIONS:
      --ktables-dir <path>   Output directory for .ktbl files.
                             Default: data/hitran_kdist
      --lut-file    <path>   Output path for nexim_v1.lut.
                             Default: data/lut/nexim_v1.lut
      --threads     <n>      Degree of parallelism.
                             Default: all logical processors
      --help                 Show this message.
    """);
}

