using System;
using System.Diagnostics;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using NEXIM.Core.Interfaces;
using NEXIM.Core.Models;

namespace NEXIM.Core.Atmospheric.LUT;

/// <summary>
/// Mode 1 FAST atmospheric radiative transfer using a pre-computed LUT.
///
/// Accuracy:  ±5–10% (vs. MODTRAN-class) — suitable for quick scene previews
///            and parameter sweeps.
/// Speed:     &lt;10 ms per scene pixel (multilinear interpolation only).
/// LUT size:  ~50 MB stored in <c>data/lut/nexim_v1.lut</c>.
///
/// The LUT is indexed by:
///   SZA (11 nodes), VZA (9 nodes), AOD (7 nodes), WVC (8 nodes), λ (250 nodes)
///
/// Three output fields per grid point:
///   [0] Transmittance (direct + diffuse)
///   [1] Path radiance [W m⁻² sr⁻¹ µm⁻¹] / (F_sol / π) — normalised to unit solar
///   [2] Downwelling irradiance at surface / F_sol
///
/// The LUT was generated by NEXIM.LutGen using Mode 2 (CKD+DISORT 8-stream)
/// over a US Standard Atmosphere with varying AOD and WVC.
/// </summary>
public sealed class FastAtmosphericRT : IAtmosphericRT
{
    private readonly LutInterpolator _lut;

    /// <inheritdoc/>
    public string ModeName => "FAST (LUT multilinear interpolation)";

    /// <summary>
    /// Create the Mode 1 solver.
    /// </summary>
    /// <param name="lutFilePath">
    /// Path to the <c>.lut</c> file. Typically <c>data/lut/nexim_v1.lut</c>.
    /// </param>
    public FastAtmosphericRT(string lutFilePath)
    {
        ArgumentException.ThrowIfNullOrEmpty(lutFilePath);
        if (!File.Exists(lutFilePath))
            throw new FileNotFoundException(
                $"LUT file not found: {lutFilePath}. " +
                "Run NEXIM.LutGen to generate it or download from the project releases.", lutFilePath);

        var (format, data) = LutLoader.LoadFromFile(lutFilePath);
        _lut = new LutInterpolator(format, data);
    }

    /// <summary>
    /// Create the Mode 1 solver from an already-loaded LUT interpolator.
    /// Used in unit tests and the LutGen tool.
    /// </summary>
    public FastAtmosphericRT(LutInterpolator lut)
    {
        _lut = lut ?? throw new ArgumentNullException(nameof(lut));
    }

    /// <inheritdoc/>
    public async Task<RadianceResult> ComputeAsync(
        AtmosphericInput  input,
        CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(input);
        var sw = Stopwatch.StartNew();

        var result = await Task.Run(() => ComputeCore(input, ct), ct);

        sw.Stop();
        return new RadianceResult
        {
            UpwellingRadiance     = result.UpwellingRadiance,
            DownwellingIrradiance = result.DownwellingIrradiance,
            PathRadiance          = result.PathRadiance,
            Transmittance         = result.Transmittance,
            Grid                  = result.Grid,
            ComputeTime_ms        = sw.Elapsed.TotalMilliseconds,
            ModeName              = result.ModeName,
        };
    }

    /// <inheritdoc/>
    public double EstimateComputeTime_ms(AtmosphericInput input)
        => 0.04 * input.Grid.Count + 0.5; // empirical: ~0.04 ms/band + 0.5 ms overhead

    private RadianceResult ComputeCore(AtmosphericInput input, CancellationToken ct)
    {
        int nBands = input.Grid.Count;
        var upwelling     = new double[nBands];
        var downwelling   = new double[nBands];
        var pathRadiance  = new double[nBands];
        var transmittance = new double[nBands];

        double sza  = input.Geometry.SolarZenith_deg;
        double vza  = input.Geometry.ViewZenith_deg;
        double aod  = input.Aerosol.Aod550;

        // Effective WVC: use profile H₂O total column (g/cm²)
        double wvc = GetProfileWvc(input.Profile);

        for (int ib = 0; ib < nBands; ib++)
        {
            ct.ThrowIfCancellationRequested();

            double wl  = input.Grid.Wavelengths_um[ib];
            double rho = input.SurfaceReflectance.Length == 1
                ? input.SurfaceReflectance[0]
                : input.SurfaceReflectance[ib];
            rho = Math.Clamp(rho, 0.0, 1.0);

            // Query LUT
            double[] fields = _lut.Interpolate(sza, vza, aod, wvc, wl);

            double T     = fields[LutInterpolator.FieldTransmittance];
            double Lpath = fields[LutInterpolator.FieldPathRadiance];
            double fDown = fields[LutInterpolator.FieldDownwelling];

            // Solar irradiance at this wavelength (same Planck-based approx as AccurateRT)
            double fSol = SolarIrradiance_Wm2um(wl);

            // Reconstruct physical radiance:
            //   L_up = L_path + T × ρ/π × (F_sol × cos(SZA))  [Lambertian surface]
            double mu0 = Math.Cos(sza * Math.PI / 180.0);
            double lup = Lpath * fSol + T * rho / Math.PI * fSol * mu0;

            upwelling[ib]     = Math.Max(0, lup);
            downwelling[ib]   = Math.Max(0, fDown * fSol);
            pathRadiance[ib]  = Math.Max(0, Lpath * fSol);
            transmittance[ib] = Math.Clamp(T, 0, 1);
        }

        return new RadianceResult
        {
            UpwellingRadiance     = upwelling,
            DownwellingIrradiance = downwelling,
            PathRadiance          = pathRadiance,
            Transmittance         = transmittance,
            Grid                  = input.Grid,
            ComputeTime_ms        = 0,
            ModeName              = ModeName,
        };
    }

    private static double GetProfileWvc(AtmosphericProfile profile)
    {
        if (profile.CustomLayers is null) return 1.5; // US Standard default ~1.5 g/cm²
        double total = 0;
        foreach (var l in profile.CustomLayers) total += l.H2O_g_cm2;
        return total;
    }

    private static double SolarIrradiance_Wm2um(double lambda_um)
    {
        const double scaleFactor = 2.158e-5 * Math.PI;
        return scaleFactor * PlanckRadiance(lambda_um, 5778.0);
    }

    private static double PlanckRadiance(double lambda_um, double T)
    {
        const double c1 = 1.1910429e-16;
        const double c2 = 0.014387769;
        if (T <= 0) return 0;
        double lm = lambda_um * 1e-6;
        double exp = c2 / (lm * T);
        if (exp > 700) return 0;
        return c1 / (Math.Pow(lm, 5) * (Math.Exp(exp) - 1.0)) * 1e-6;
    }
}
